language: cpp
sudo: reguired
os:
    - windows
compiler:
    - gcc
    - clang
script:
  - cd /cbp2ndk/dist
  - mkdir -p test
  - cd test
  - cmake -G"Unix Makefiles" .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config "Debug"
