language: cpp
sudo: reguired
os:
    - windows
compiler:
    - gcc
script:
  - dir
  - cd cbp2ndk/dist
  - mkdir -p test
  - cd test
  - cmake -G"MinGW Makefiles" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"
  - cmake --build . --config "Debug"
  - dir
before_deploy:
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-cbp2ndk-${TRAVIS_BUILD_NUMBER}.tar.gz cbp2ndk.exe
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}${REPO}-cbp2ndk-${TRAVIS_BUILD_NUMBER}.tar.gz
  on:
    all_branches: true
    tags: false
