language: cpp
sudo: reguired
os:
    - windows
compiler:
    - gcc
script:
  - dir
  - cd cbp2ndk/dist
  - mkdir -p test
  - cd test
  - cmake -G"MinGW Makefiles" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"
  - cmake --build . --config "Debug"
  - dir
  - cbp2ndk.exe -v -a
