language: cpp
sudo: reguired
os:
    - windows
compiler:
    - gcc
script:
  - dir
  - cd cbp2ndk/dist
  - mkdir -p test
  - cd test
  - cmake -G"MinGW Makefiles" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"
  - cmake --build . --config "Debug"
  - dir
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}
before_deploy:
  - dir
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "cbp2ndk/dist/test/cbp2ndk.exe"
  on:
    tags: false
